KST_EVAL_EDGE = 2
KST_EVAL_ANGLE = 1
# 这里斜投和正投的步数不一致，需要注意
AF_CAL_MOTOR_THRESHOLD = 1000
CAL_PROGRESS_STEP = 5
DIS_STEPS_0 = 1000
DIS_STEPS_1 = 1000
DEV_LOCATION_STEPS = 1399
DEV_AF_CAL_STEPS_OFFSET = -68
IMU_GAP = 10
ROTATE_DELAY = 3.6

KST_FILE_CSV_NAME = 'asuFiles/kst_cal_data.csv'

AF_FILE_CSV_NAME = 'result/af_cal_data.csv'
